function loophalaman(b){var c="";nomerkiri=parseInt(numshowpage/2);nomerkiri==numshowpage-nomerkiri&&(numshowpage=2*nomerkiri+1);mulai=nomerhal-nomerkiri;1>mulai&&(mulai=1);maksimal=parseInt(b/postperpage)+1;maksimal-1==b/postperpage&&--maksimal;akhir=mulai+numshowpage-1;akhir>maksimal&&(akhir=maksimal);c+="<span class='showpageOf'>Page "+nomerhal+" of "+maksimal+"</span>";b=parseInt(nomerhal)-1;1<nomerhal&&(c+=2==nomerhal?"page"==jenis?'<span class="showpage"><a href="'+home_page+'">'+upPageWord+
"</a></span>":'<span class="showpageNum"><a href="/search/label/'+lblname1+"?&max-results="+postperpage+'">'+upPageWord+"</a></span>":"page"==jenis?'<span class="showpageNum"><a href="#" onclick="redirectpage('+b+');return false">'+upPageWord+"</a></span>":'<span class="showpageNum"><a href="#" onclick="redirectlabel('+b+');return false">'+upPageWord+"</a></span>");1<mulai&&(c+="page"==jenis?'<span class="showpageNum"><a href="'+home_page+'">1</a></span>':'<span class="showpageNum"><a href="/search/label/'+
lblname1+"?&max-results="+postperpage+'">1</a></span>');2<mulai&&(c+="");for(b=mulai;b<=akhir;b++)c+=nomerhal==b?'<span class="showpagePoint">'+b+"</span>":1==b?"page"==jenis?'<span class="showpageNum"><a href="'+home_page+'">1</a></span>':'<span class="showpageNum"><a href="/search/label/'+lblname1+"?&max-results="+postperpage+'">1</a></span>':"page"==jenis?'<span class="showpageNum"><a href="#" onclick="redirectpage('+b+');return false">'+b+"</a></span>":'<span class="showpageNum"><a href="#" onclick="redirectlabel('+
b+');return false">'+b+"</a></span>";akhir<maksimal-1&&(c+="");akhir<maksimal&&(c+="page"==jenis?'<span class="showpageNum"><a href="#" onclick="redirectpage('+maksimal+');return false">'+maksimal+"</a></span>":'<span class="showpageNum"><a href="#" onclick="redirectlabel('+maksimal+');return false">'+maksimal+"</a></span>");b=parseInt(nomerhal)+1;nomerhal<maksimal&&(c+="page"==jenis?'<span class="showpageNum"><a href="#" onclick="redirectpage('+b+');return false">'+downPageWord+"</a></span>":'<span class="showpageNum"><a href="#" onclick="redirectlabel('+
b+');return false">'+downPageWord+"</a></span>");b=document.getElementsByName("pageArea");for(var r=document.getElementById("blog-pager"),f=0;f<b.length;f++)b[f].innerHTML=c;b&&0<b.length&&(c="");r&&(r.innerHTML=c)}function hitungtotaldata(b){b=parseInt(b.feed.openSearch$totalResults.$t,10);loophalaman(b)}
function halamanblogger(){var b=urlactivepage;-1!=b.indexOf("/search/label/")&&(lblname1=-1!=b.indexOf("?updated-max")?b.substring(b.indexOf("/search/label/")+14,b.indexOf("?updated-max")):b.substring(b.indexOf("/search/label/")+14,b.indexOf("?&max")));-1==b.indexOf("?q=")&&-1==b.indexOf(".html")&&(-1==b.indexOf("/search/label/")?(jenis="page",nomerhal=-1!=urlactivepage.indexOf("#PageNo=")?urlactivepage.substring(urlactivepage.indexOf("#PageNo=")+8,urlactivepage.length):1,document.write('<script src="'+
home_page+'feeds/posts/summary?max-results=1&alt=json-in-script&callback=hitungtotaldata">\x3c/script>')):(jenis="label",-1==b.indexOf("&max-results=")&&(postperpage=20),nomerhal=-1!=urlactivepage.indexOf("#PageNo=")?urlactivepage.substring(urlactivepage.indexOf("#PageNo=")+8,urlactivepage.length):1,document.write('<script src="'+home_page+"feeds/posts/summary/-/"+lblname1+'?alt=json-in-script&callback=hitungtotaldata&max-results=1" >\x3c/script>')))}
function redirectpage(b){jsonstart=(b-1)*postperpage;nopage=b;b=document.getElementsByTagName("head")[0];var c=document.createElement("script");c.type="text/javascript";c.setAttribute("src",home_page+"feeds/posts/summary?start-index="+jsonstart+"&max-results=1&alt=json-in-script&callback=finddatepost");b.appendChild(c)}
function redirectlabel(b){jsonstart=(b-1)*postperpage;nopage=b;b=document.getElementsByTagName("head")[0];var c=document.createElement("script");c.type="text/javascript";c.setAttribute("src",home_page+"feeds/posts/summary/-/"+lblname1+"?start-index="+jsonstart+"&max-results=1&alt=json-in-script&callback=finddatepost");b.appendChild(c)}
function finddatepost(b){post=b.feed.entry[0];b=post.published.$t.substring(0,19)+post.published.$t.substring(23,29);b=encodeURIComponent(b);location.href="page"==jenis?"/search?updated-max="+b+"&max-results="+postperpage+"#PageNo="+nopage:"/search/label/"+lblname1+"?updated-max="+b+"&max-results="+postperpage+"#PageNo="+nopage}var nopage,jenis,nomerhal,lblname1;halamanblogger();(function(b,c,r){function f(a,t,la){a=c.createElement(a);return t&&(a.id=m+t),la&&(a.style.cssText=la),b(a)}function Y(){return r.innerHeight?r.innerHeight:b(r).height()}function Q(a,t){t!==Object(t)&&(t={});this.cache={};this.el=a;this.value=function(a){var d;return void 0===this.cache[a]&&(d=b(this.el).attr("data-cbox-"+a),void 0!==d?this.cache[a]=d:void 0!==t[a]?this.cache[a]=t[a]:void 0!==Z[a]&&(this.cache[a]=Z[a])),this.cache[a]};this.get=function(a){a=this.value(a);return b.isFunction(a)?a.call(this.el,
this):a}}function R(a){var b=n.length;a=(q+a)%b;return 0>a?b+a:a}function l(a,b){return Math.round((/%/.test(a)?("x"===b?B.width():Y())/100:1)*parseInt(a,10))}function ma(a,b){return a.get("photo")||a.get("photoRegex").test(b)}function na(a,b){return a.get("retinaUrl")&&1<r.devicePixelRatio?b.replace(a.get("photoRegex"),a.get("retinaSuffix")):b}function oa(a){"contains"in g[0]&&!g[0].contains(a.target)&&a.target!==C[0]&&(a.stopPropagation(),g.focus())}function K(a){K.str!==a&&(g.add(C).removeClass(K.str).addClass(a),
K.str=a)}function ta(d){q=0;d&&!1!==d&&"nofollow"!==d?(n=b("."+I).filter(function(){var a=b.data(this,v);return(new Q(this,a)).get("rel")===d}),q=n.index(a.el),-1===q&&(n=n.add(a.el),q=n.length-1)):n=b(a.el)}function G(a){b(c).trigger(a);y.triggerHandler(a)}function S(d){var t;if(!L){if(t=b(d).data(v),a=new Q(d,t),ta(a.get("rel")),!D){D=M=!0;K(a.get("className"));g.css({visibility:"hidden",display:"block",opacity:""});k=f(h,"LoadedContent","width:0; height:0; overflow:hidden; visibility:hidden");
w.css({width:"",height:""}).append(k);z=aa.height()+ba.height()+w.outerHeight(!0)-w.height();A=ca.width()+da.width()+w.outerWidth(!0)-w.width();E=k.outerHeight(!0);F=k.outerWidth(!0);d=l(a.get("initialWidth"),"x");t=l(a.get("initialHeight"),"y");var e=a.get("maxWidth"),u=a.get("maxHeight");a.w=(!1!==e?Math.min(d,l(e,"x")):d)-F-A;a.h=(!1!==u?Math.min(t,l(u,"y")):t)-E-z;k.css({width:"",height:a.h});p.position();G(ua);a.get("onOpen");ea.add(fa).hide();g.focus();a.get("trapFocus")&&c.addEventListener&&
(c.addEventListener("focus",oa,!0),y.one(ga,function(){c.removeEventListener("focus",oa,!0)}));a.get("returnFocus")&&y.one(ga,function(){b(a.el).focus()})}d=parseFloat(a.get("opacity"));C.css({opacity:d===d?d:"",cursor:a.get("overlayClose")?"pointer":"",visibility:"visible"}).show();a.get("closeButton")?T.html(a.get("close")).appendTo(w):T.appendTo("<div/>");va()}}function pa(){g||(ha=!1,B=b(r),g=f(h).attr({id:v,"class":!1===b.support.opacity?m+"IE":"",role:"dialog",tabindex:"-1"}).hide(),C=f(h,"Overlay").hide(),
U=b([f(h,"LoadingOverlay")[0],f(h,"LoadingGraphic")[0]]),H=f(h,"Wrapper"),w=f(h,"Content").append(fa=f(h,"Title"),ia=f(h,"Current"),N=b('<button type="button"/>').attr({id:m+"Previous"}),O=b('<button type="button"/>').attr({id:m+"Next"}),J=f("button","Slideshow"),U),T=b('<button type="button"/>').attr({id:m+"Close"}),H.append(f(h).append(f(h,"TopLeft"),aa=f(h,"TopCenter"),f(h,"TopRight")),f(h,!1,"clear:left").append(ca=f(h,"MiddleLeft"),w,da=f(h,"MiddleRight")),f(h,!1,"clear:left").append(f(h,"BottomLeft"),
ba=f(h,"BottomCenter"),f(h,"BottomRight"))).find("div div").css({"float":"left"}),P=f(h,!1,"position:absolute; width:9999px; visibility:hidden; display:none; max-width:none;"),ea=O.add(N).add(ia).add(J));c.body&&!g.parent().length&&b(c.body).append(C,g.append(H,P))}function wa(){function d(a){1<a.which||a.shiftKey||a.altKey||a.metaKey||a.ctrlKey||(a.preventDefault(),S(this))}return g?(ha||(ha=!0,O.click(function(){p.next()}),N.click(function(){p.prev()}),T.click(function(){p.close()}),C.click(function(){a.get("overlayClose")&&
p.close()}),b(c).bind("keydown."+m,function(b){var d=b.keyCode;D&&a.get("escKey")&&27===d&&(b.preventDefault(),p.close());D&&a.get("arrowKey")&&n[1]&&!b.altKey&&(37===d?(b.preventDefault(),N.click()):39===d&&(b.preventDefault(),O.click()))}),b.isFunction(b.fn.on)?b(c).on("click."+m,"."+I,d):b("."+I).live("click."+m,d)),!0):!1}function va(){var d,c,g,u=p.prep,qa=++ja;if(M=!0,e=!1,G(V),G(W),a.get("onLoad"),a.h=a.get("height")?l(a.get("height"),"y")-E-z:a.get("innerHeight")&&l(a.get("innerHeight"),"y"),
a.w=a.get("width")?l(a.get("width"),"x")-F-A:a.get("innerWidth")&&l(a.get("innerWidth"),"x"),a.mw=a.w,a.mh=a.h,a.get("maxWidth")&&(a.mw=l(a.get("maxWidth"),"x")-F-A,a.mw=a.w&&a.w<a.mw?a.w:a.mw),a.get("maxHeight")&&(a.mh=l(a.get("maxHeight"),"y")-E-z,a.mh=a.h&&a.h<a.mh?a.h:a.mh),d=a.get("href"),ra=setTimeout(function(){U.show()},100),a.get("inline")){var k=b(d);g=b("<div>").hide().insertBefore(k);y.one(V,function(){g.replaceWith(k)});u(k)}else a.get("iframe")?u(" "):a.get("html")?u(a.get("html")):
ma(a,d)?(d=na(a,d),e=new Image,b(e).addClass(m+"Photo").bind("error",function(){u(f(h,"Error").html(a.get("imgError")))}).one("load",function(){qa===ja&&setTimeout(function(){var d;b.each(["alt","longdesc","aria-describedby"],function(d,c){var g=b(a.el).attr(c)||b(a.el).attr("data-"+c);g&&e.setAttribute(c,g)});a.get("retinaImage")&&1<r.devicePixelRatio&&(e.height/=r.devicePixelRatio,e.width/=r.devicePixelRatio);a.get("scalePhotos")&&(c=function(){e.height-=e.height*d;e.width-=e.width*d},a.mw&&e.width>
a.mw&&(d=(e.width-a.mw)/e.width,c()),a.mh&&e.height>a.mh&&(d=(e.height-a.mh)/e.height,c()));a.h&&(e.style.marginTop=Math.max(a.mh-e.height,0)/2+"px");n[1]&&(a.get("loop")||n[q+1])&&(e.style.cursor="pointer",e.onclick=function(){p.next()});e.style.width=e.width+"px";e.style.height=e.height+"px";u(e)},1)}),e.src=d):d&&P.load(d,a.get("data"),function(d,c){qa===ja&&u("error"===c?f(h,"Error").html(a.get("xhrError")):b(this).contents())})}var C,g,H,w,aa,ca,da,ba,n,B,k,P,U,fa,ia,J,O,N,T,ea,a,z,A,E,F,q,e,
D,M,L,ra,p,ha,Z={html:!1,photo:!1,iframe:!1,inline:!1,transition:"elastic",speed:300,fadeOut:300,width:!1,initialWidth:"600",innerWidth:!1,maxWidth:!1,height:!1,initialHeight:"450",innerHeight:!1,maxHeight:!1,scalePhotos:!0,scrolling:!0,opacity:.9,preloading:!0,className:!1,overlayClose:!0,escKey:!0,arrowKey:!0,top:!1,bottom:!1,left:!1,right:!1,fixed:!1,data:void 0,closeButton:!0,fastIframe:!0,open:!1,reposition:!0,loop:!0,slideshow:!1,slideshowAuto:!0,slideshowSpeed:2500,slideshowStart:"start slideshow",
slideshowStop:"stop slideshow",photoRegex:/\.(gif|png|jp(e|g|eg)|bmp|ico|webp|jxr|svg)((#|\?).*)?$/i,retinaImage:!1,retinaUrl:!1,retinaSuffix:"@2x.$1",current:"image {current} of {total}",previous:"previous",next:"next",close:"close",xhrError:"This content failed to load.",imgError:"This image failed to load.",returnFocus:!0,trapFocus:!0,onOpen:!1,onLoad:!1,onComplete:!1,onCleanup:!1,onClosed:!1,rel:function(){return this.rel},href:function(){return b(this).attr("href")},title:function(){return this.title}},
v="colorbox",m="cbox",I=m+"Element",ua=m+"_open",W=m+"_load",X=m+"_complete",ka=m+"_cleanup",ga=m+"_closed",V=m+"_purge",y=b("<a/>"),h="div",ja=0,sa={},xa=function(){function b(){clearTimeout(k)}function c(){(a.get("loop")||n[q+1])&&(b(),k=setTimeout(p.next,a.get("slideshowSpeed")))}function e(){J.html(a.get("slideshowStop")).unbind(x).one(x,u);y.bind(X,c).bind(W,b);g.removeClass(l+"off").addClass(l+"on")}function u(){b();y.unbind(X,c).unbind(W,b);J.html(a.get("slideshowStart")).unbind(x).one(x,function(){p.next();
e()});g.removeClass(l+"on").addClass(l+"off")}function f(){h=!1;J.hide();b();y.unbind(X,c).unbind(W,b);g.removeClass(l+"off "+l+"on")}var h,k,l=m+"Slideshow_",x="click."+m;return function(){h?a.get("slideshow")||(y.unbind(ka,f),f()):a.get("slideshow")&&n[1]&&(h=!0,y.one(ka,f),a.get("slideshowAuto")?e():u(),J.show())}}();b[v]||(b(pa),p=b.fn[v]=b[v]=function(a,c){var g,e=this;if(a=a||{},b.isFunction(e))e=b("<a/>"),a.open=!0;else if(!e[0])return e;return e[0]?(pa(),wa()&&(c&&(a.onComplete=c),e.each(function(){var c=
b.data(this,v)||{};b.data(this,v,b.extend(c,a))}).addClass(I),g=new Q(e[0],a),g.get("open")&&S(e[0])),e):e},p.position=function(d,c){function e(){aa[0].style.width=ba[0].style.width=w[0].style.width=parseInt(g[0].style.width,10)-A+"px";w[0].style.height=ca[0].style.height=da[0].style.height=parseInt(g[0].style.height,10)-z+"px"}var f,h,k,n=0,q=0,x=g.offset();if(B.unbind("resize."+m),g.css({top:-9E4,left:-9E4}),h=B.scrollTop(),k=B.scrollLeft(),a.get("fixed")?(x.top-=h,x.left-=k,g.css({position:"fixed"})):
(n=h,q=k,g.css({position:"absolute"})),q+=!1!==a.get("right")?Math.max(B.width()-a.w-F-A-l(a.get("right"),"x"),0):!1!==a.get("left")?l(a.get("left"),"x"):Math.round(Math.max(B.width()-a.w-F-A,0)/2),n+=!1!==a.get("bottom")?Math.max(Y()-a.h-E-z-l(a.get("bottom"),"y"),0):!1!==a.get("top")?l(a.get("top"),"y"):Math.round(Math.max(Y()-a.h-E-z,0)/2),g.css({top:x.top,left:x.left,visibility:"visible"}),H[0].style.width=H[0].style.height="9999px",f={width:a.w+F+A,height:a.h+E+z,top:n,left:q},d){var r=0;b.each(f,
function(a){return f[a]!==sa[a]?(r=d,void 0):void 0});d=r}sa=f;d||g.css(f);g.dequeue().animate(f,{duration:d||0,complete:function(){e();M=!1;H[0].style.width=a.w+F+A+"px";H[0].style.height=a.h+E+z+"px";a.get("reposition")&&setTimeout(function(){B.bind("resize."+m,p.position)},1);b.isFunction(c)&&c()},step:e})},p.resize=function(b){var c;D&&(b=b||{},b.width&&(a.w=l(b.width,"x")-F-A),b.innerWidth&&(a.w=l(b.innerWidth,"x")),k.css({width:a.w}),b.height&&(a.h=l(b.height,"y")-E-z),b.innerHeight&&(a.h=l(b.innerHeight,
"y")),b.innerHeight||b.height||(c=k.scrollTop(),k.css({height:"auto"}),a.h=k.height()),k.css({height:a.h}),c&&k.scrollTop(c),p.position("none"===a.get("transition")?0:a.get("speed")))},p.prep=function(d){if(D){var l,r="none"===a.get("transition")?0:a.get("speed");k.remove();k=f(h,"LoadedContent").append(d);k.hide().appendTo(P.show()).css({width:(a.w=a.w||k.width(),a.w=a.mw&&a.mw<a.w?a.mw:a.w,a.w),overflow:a.get("scrolling")?"auto":"hidden"}).css({height:(a.h=a.h||k.height(),a.h=a.mh&&a.mh<a.h?a.mh:
a.h,a.h)}).prependTo(w);P.hide();b(e).css({"float":"none"});K(a.get("className"));l=function(){function e(){!1===b.support.opacity&&g[0].style.removeAttribute("filter")}var d,f,h=n.length;D&&(f=function(){clearTimeout(ra);U.hide();G(X);a.get("onComplete")},fa.html(a.get("title")).show(),k.show(),1<h?("string"==typeof a.get("current")&&ia.html(a.get("current").replace("{current}",q+1).replace("{total}",h)).show(),O[a.get("loop")||h-1>q?"show":"hide"]().html(a.get("next")),N[a.get("loop")||q?"show":
"hide"]().html(a.get("previous")),xa(),a.get("preloading")&&b.each([R(-1),R(1)],function(){var a,d=n[this],d=new Q(d,b.data(d,v)),e=d.get("href");e&&ma(d,e)&&(e=na(d,e),a=c.createElement("img"),a.src=e)})):ea.hide(),a.get("iframe")?(d=c.createElement("iframe"),"frameBorder"in d&&(d.frameBorder=0),"allowTransparency"in d&&(d.allowTransparency="true"),a.get("scrolling")||(d.scrolling="no"),b(d).attr({src:a.get("href"),name:(new Date).getTime(),"class":m+"Iframe",allowFullScreen:!0}).one("load",f).appendTo(k),
y.one(V,function(){d.src="//about:blank"}),a.get("fastIframe")&&b(d).trigger("load")):f(),"fade"===a.get("transition")?g.fadeTo(r,1,e):e())};"fade"===a.get("transition")?g.fadeTo(r,0,function(){p.position(0,l)}):p.position(r,l)}},p.next=function(){!M&&n[1]&&(a.get("loop")||n[q+1])&&(q=R(1),S(n[q]))},p.prev=function(){!M&&n[1]&&(a.get("loop")||q)&&(q=R(-1),S(n[q]))},p.close=function(){D&&!L&&(L=!0,D=!1,G(ka),a.get("onCleanup"),B.unbind("."+m),C.fadeTo(a.get("fadeOut")||0,0),g.stop().fadeTo(a.get("fadeOut")||
0,0,function(){g.hide();C.hide();G(V);k.remove();setTimeout(function(){L=!1;G(ga);a.get("onClosed")},1)}))},p.remove=function(){g&&(g.stop(),b[v].close(),g.stop(!1,!0).remove(),C.remove(),L=!1,g=null,b("."+I).removeData(v).removeClass(I),b(c).unbind("click."+m).unbind("keydown."+m))},p.element=function(){return b(a.el)},p.settings=Z)})(jQuery,document,window);function hello(b){alert("Hello, "+b)}hello("New user");
